#!/usr/bin/env python3

import sys
import csv


HEADER = (
    'domain',
    'entity',
    'attribute',
    'value',
)


def main():
    w = csv.writer(sys.stdout)
    w.writerow(HEADER)

    for i in range(3):
        for j in range(4):
            for k in range(5):
                for p in range(6):
                    w.writerow((
                        'domain' + str(i),
                        'entity' + str(j),
                        'attr' + str(k),
                        'value' + str(p),
                    ))
    sys.stdout.flush()


if __name__ == '__main__':
    main()
